<a href="https://colab.research.google.com/github/yashpatil1805/datasciencecodsoft/blob/main/Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.preprocessing import LabelEncoder


In [ ]:
df=pd.read_csv('/content/IRIS.csv')

In [ ]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
label_encoder=LabelEncoder()
df['species']=label_encoder.fit_transform(df['species'])

In [ ]:
df.head(100)

sepal_length  sepal_width  petal_length  petal_width  species
0            5.1          3.5           1.4          0.2        0
1            4.9          3.0           1.4          0.2        0
2            4.7          3.2           1.3          0.2        0
3            4.6          3.1           1.5          0.2        0
4            5.0          3.6           1.4          0.2        0
..           ...          ...           ...          ...      ...
95           5.7          3.0           4.2          1.2        1
96           5.7          2.9           4.2          1.3        1
97           6.2          2.9           4.3          1.3        1
98           5.1          2.5           3.0          1.1        1
99           5.7          2.8           4.1          1.3        1

[100 rows x 5 columns]

In [ ]:
x=df.drop('species',axis=1)
y=df['species']

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=2)


In [ ]:
logreg_model=LogisticRegression(max_iter=1000)
logreg_model.fit(xtrain,ytrain)


LogisticRegression(max_iter=1000)

In [ ]:
ypred=logreg_model.predict(xtest)
accuracy=accuracy_score(ytest,ypred)

In [ ]:
accuracy*100

96.66666666666667

In [ ]:
print('Classification Report:')
print(classification_report(ytest,ypred))

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.88      0.93         8
           2       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30



In [ ]:
print("confusion Matrix:")
print(confusion_matrix(ytest,ypred))

confusion Matrix:
[[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]


In [ ]:
def predict_species(model, sepal_length, sepal_width, petal_length, petal_width):
    # Convert user input into a DataFrame
    input_data = pd.DataFrame({
        'sepal_length': [sepal_length],
        'sepal_width': [sepal_width],
        'petal_length': [petal_length],
        'petal_width': [petal_width]
    })
    # Make prediction
    predicted_species = model.predict(input_data)
    return label_encoder.inverse_transform(predicted_species)[0]

# Take user input
sepal_length = float(input("Enter sepal length: "))
sepal_width = float(input("Enter sepal width: "))
petal_length = float(input("Enter petal length: "))
petal_width = float(input("Enter petal width: "))

# Predict species
predicted_species = predict_species(logreg_model, sepal_length, sepal_width, petal_length, petal_width)
print("Predicted species:", predicted_species)


Enter sepal length: 3
Enter sepal width: 3.4
Enter petal length: 1.2
Enter petal width: 2
Predicted species: Iris-setosa
